definitions:
  config:
    /hst:hst/hst:configurations/hippoaddoncrispdemo/hst:sitemap:
      jcr:primaryType: hst:sitemap
      /root:
        jcr:primaryType: hst:sitemapitem
        hst:componentconfigurationid: hst:pages/homepage
        hst:refId: root
      /_any_:
        jcr:primaryType: hst:sitemapitem
        hst:componentconfigurationid: hst:pages/pagenotfound
      /pagenotfound:
        jcr:primaryType: hst:sitemapitem
        hst:componentconfigurationid: hst:pages/pagenotfound
        hst:refId: pagenotfound
      /events:
        jcr:primaryType: hst:sitemapitem
        hst:componentconfigurationid: hst:pages/eventslist
        hst:relativecontentpath: events
        /_any_.html:
          jcr:primaryType: hst:sitemapitem
          hst:componentconfigurationid: hst:pages/eventspage
          hst:relativecontentpath: ${parent}/${1}
        /_any_:
          jcr:primaryType: hst:sitemapitem
          hst:componentconfigurationid: hst:pages/eventslist
          hst:relativecontentpath: ${parent}/${1}
      /news:
        jcr:primaryType: hst:sitemapitem
        hst:componentconfigurationid: hst:pages/newslist
        hst:relativecontentpath: news
        /_any_.html:
          jcr:primaryType: hst:sitemapitem
          hst:componentconfigurationid: hst:pages/newspage
          hst:relativecontentpath: ${parent}/${1}
        /_any_:
          jcr:primaryType: hst:sitemapitem
          hst:componentconfigurationid: hst:pages/newslist
          hst:relativecontentpath: ${parent}/${1}
