definitions:
  config:
    /hst:hst/hst:configurations/hippoaddoncrispdemo/hst:templates:
      jcr:primaryType: hst:templates
      /base-layout:
        jcr:primaryType: hst:template
        hst:renderpath: webfile:/freemarker/hippoaddoncrispdemo/base-layout.ftl
      /base-top-menu:
        jcr:primaryType: hst:template
        hst:renderpath: webfile:/freemarker/hippoaddoncrispdemo/base-top-menu.ftl
      /base-footer:
        jcr:primaryType: hst:template
        hst:renderpath: webfile:/freemarker/hippoaddoncrispdemo/base-footer.ftl
      /homepage-main:
        jcr:primaryType: hst:template
        hst:renderpath: webfile:/freemarker/hippoaddoncrispdemo/homepage-main.ftl
      /pagenotfound-main:
        jcr:primaryType: hst:template
        hst:renderpath: webfile:/freemarker/hippoaddoncrispdemo/pagenotfound-main.ftl
      /eventspage-main:
        jcr:primaryType: hst:template
        hst:renderpath: webfile:/freemarker/hstdefault/eventspage-main.ftl
      /newspage-main:
        jcr:primaryType: hst:template
        hst:renderpath: webfile:/freemarker/hstdefault/newspage-main.ftl
