definitions:
  config:
    /hst:hst/hst:sites:
      .meta:residual-child-node-category: content
      jcr:primaryType: hst:sites
      /hippoaddoncrispdemo:
        jcr:primaryType: hst:site
        hst:content: /content/documents/hippoaddoncrispdemo
