definitions:
  config:
    /hippo:configuration/hippo:domains/hstconfig:
      jcr:primaryType: hipposys:domain
      /readwrite:
        jcr:primaryType: hipposys:authrole
        hipposys:groups: [webmaster]
        hipposys:role: readwrite
      /hst-descriptive:
        jcr:primaryType: hipposys:domainrule
        /type-hst-descriptive:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:descriptive
      /hst-template:
        jcr:primaryType: hipposys:domainrule
        /type-hst-template:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:template
      /hst-templates:
        jcr:primaryType: hipposys:domainrule
        /type-hst-templates:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:templates
      /hst-abstractcomponent:
        jcr:primaryType: hipposys:domainrule
        /type-hst-abstractcomponent:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:abstractcomponent
      /hst-component:
        jcr:primaryType: hipposys:domainrule
        /type-hst-component:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:component
      /hst-containeritemcomponent:
        jcr:primaryType: hipposys:domainrule
        /type-hst-containeritemcomponent:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:containeritemcomponent
      /hst-containercomponent:
        jcr:primaryType: hipposys:domainrule
        /type-hst-containercomponent:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:containercomponent
      /hst-containercomponentreference:
        jcr:primaryType: hipposys:domainrule
        /type-hst-containtercomponent:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:containercomponentreference
      /hst-containteritempackage:
        jcr:primaryType: hipposys:domainrule
        /type-hst-containeritempackage:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:containeritempackage
      /hst-catalog:
        jcr:primaryType: hipposys:domainrule
        /type-hst-catalog:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:catalog
      /hst-components:
        jcr:primaryType: hipposys:domainrule
        /type-hst-components:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:components
      /hst-pages:
        jcr:primaryType: hipposys:domainrule
        /type-hst-pages:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:pages
      /hst-sitemap:
        jcr:primaryType: hipposys:domainrule
        /type-hst-sitemap:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:sitemap
      /hst-sitemapitem:
        jcr:primaryType: hipposys:domainrule
        /type-hst-sitemapitem:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:sitemapitem
      /hst-sitemapitemhandler:
        jcr:primaryType: hipposys:domainrule
        /type-hst-sitemapitemhandler:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:sitemapitemhandler
      /hst-sitemapitemhandlers:
        jcr:primaryType: hipposys:domainrule
        /type-hst-sitemapitemhandlers:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:sitemapitemhandlers
      /hst-sitemenuitem:
        jcr:primaryType: hipposys:domainrule
        /type-hst-sitemenuitem:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:sitemenuitem
      /hst-sitemenu:
        jcr:primaryType: hipposys:domainrule
        /type-hst-sitemenu:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:sitemenu
      /hst-sitemenus:
        jcr:primaryType: hipposys:domainrule
        /type-hst-sitemenus:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:sitemenus
      /hst-configuration:
        jcr:primaryType: hipposys:domainrule
        /type-hst-configuration:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:configuration
      /hst-configurations:
        jcr:primaryType: hipposys:domainrule
        /type-hst-configurations:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:configurations
      /hst-site:
        jcr:primaryType: hipposys:domainrule
        /type-hst-site:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:site
      /hst-sites:
        jcr:primaryType: hipposys:domainrule
        /type-hst-sites:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:sites
      /hst-primarydomain:
        jcr:primaryType: hipposys:domainrule
        /type-hst-primarydomain:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:primarydomain
      /hst-redirectdomain:
        jcr:primaryType: hipposys:domainrule
        /type-hst-redirectdomain:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:redirectdomain
      /hst-mount:
        jcr:primaryType: hipposys:domainrule
        /type-hst-mount:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:mount
      /hst-portmount:
        jcr:primaryType: hipposys:domainrule
        /type-hst-portmount:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:portmount
      /hst-virtualhost:
        jcr:primaryType: hipposys:domainrule
        /type-hst-virtualhost:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:virtualhost
      /hst-virtualhostgroup:
        jcr:primaryType: hipposys:domainrule
        /type-hst-virtualhostgroup:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:virtualhostgroup
      /hst-virtualhosts:
        jcr:primaryType: hipposys:domainrule
        /type-hst-virtualhosts:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:virtualhosts
      /hst-blueprint:
        jcr:primaryType: hipposys:domainrule
        /type-hst-blueprint:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:blueprint
      /hst-blueprints:
        jcr:primaryType: hipposys:domainrule
        /type-hst-blueprints:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:blueprints
      /hst-hst:
        jcr:primaryType: hipposys:domainrule
        /type-hst-hst:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:hst
      /hst-contentshare:
        jcr:primaryType: hipposys:domainrule
        /type-hst-contentshare:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:contentshare
      /hst-channel:
        jcr:primaryType: hipposys:domainrule
        /type-hst-channel:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:channel
      /hst-channels:
        jcr:primaryType: hipposys:domainrule
        /type-hst-channels:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:channels
      /hst-channelinfo:
        jcr:primaryType: hipposys:domainrule
        /type-hst-channelinfo:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:channelinfo
      /hst-workspace:
        jcr:primaryType: hipposys:domainrule
        /type-hst-workspace:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:workspace
      /hst-containercomponentfolder:
        jcr:primaryType: hipposys:domainrule
        /type-hst-containercomponentfolder:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:primaryType
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hst:containercomponentfolder
