#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
#set($hyphen = '-')
#set($empty = '')
definitions:
  config:
    /hst:${rootArtifactId.replace($hyphen,$empty)}/hst:configurations:
      /common:
        jcr:primaryType: hst:configuration
        /hst:sitemap:
          jcr:primaryType: hst:sitemap
        /hst:abstractpages:
          jcr:primaryType: hst:pages
        /hst:pages:
          jcr:primaryType: hst:pages
        /hst:components:
          jcr:primaryType: hst:components
        /hst:templates:
          jcr:primaryType: hst:templates
        /hst:sitemenus:
          jcr:primaryType: hst:sitemenus
        /hst:sitemapitemhandlers:
          jcr:primaryType: hst:sitemapitemhandlers
        /hst:catalog:
          jcr:primaryType: hst:catalog
      /${rootArtifactId.replace($hyphen,$empty)}:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
