definitions:
  config:
    /hippo:configuration/hippo:frontend/cms/cms-services/navAppSettingsService:
      jcr:primaryType: frontend:plugin
      plugin.class: org.hippoecm.frontend.service.navappsettings.NavAppSettingsService



