definitions:
  config:
    /hippo:configuration/hippo:frontend/cms/cms-dashshortcuts/changePasswordShortcut:
      jcr:primaryType: frontend:plugin
      passwordexpirationnotificationdays: 3.0
      plugin.class: org.hippoecm.frontend.plugins.cms.admin.plugins.ChangePasswordShortcutPlugin
      wicket.id: shortcut
      workaround: 5
