definitions:
  config:
    /hippo:configuration/hippo:workflows/shortcuts:
      jcr:primaryType: hipposys:workflowcategory
      /folder:
        jcr:primaryType:
          operation: override
          type: name
          value: frontend:workflow
        /frontend:renderer:
          jcr:primaryType: frontend:plugin
          plugin.class: org.hippoecm.frontend.plugins.standardworkflow.NullWorkflowPlugin
      /directory:
        jcr:primaryType:
          operation: override
          type: name
          value: frontend:workflow
        /frontend:renderer:
          jcr:primaryType: frontend:plugin
          plugin.class: org.hippoecm.frontend.plugins.standardworkflow.NullWorkflowPlugin
      /gallery:
        .meta:order-before: folder
        jcr:primaryType: frontend:workflow
        hipposys:classname: org.hippoecm.repository.gallery.impl.GalleryWorkflowImpl
        hipposys:display: Shortcut workflow on gallery folders
        hipposys:nodetype: hippostd:gallery
        hipposys:privileges: ['hippo:author']
        /hipposys:types:
          jcr:primaryType: hipposys:types
        /frontend:renderer:
          jcr:primaryType: frontend:plugin
          plugin.class: org.hippoecm.frontend.plugins.standardworkflow.NullWorkflowPlugin
