definitions:
  config:
    /hst:hst/hst:configurations/hippoaddoncrispdemo/hst:pages/eventslist:
      jcr:primaryType: hst:component
      hst:referencecomponent: hst:abstractpages/base
      /main:
        jcr:primaryType: hst:containercomponentreference
        hst:referencecomponent: eventslist/main
