#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
#set($hyphen = '-')
#set($empty = '')
definitions:
  config:
    /hst:hst/hst:hosts:
      jcr:primaryType: hst:virtualhosts
      hst:defaultcontextpath: /site
      /dev-localhost:
        jcr:primaryType: hst:virtualhostgroup
        hst:cmslocation: http://localhost:8080/cms
        hst:defaultport: 8080
        /localhost:
          jcr:primaryType: hst:virtualhost
          /hst:root:
            jcr:primaryType: hst:mount
            hst:homepage: root
            hst:mountpoint: /hst:hst/hst:sites/${rootArtifactId.replace($hyphen,$empty)}
