definitions:
  config:
    /hippo:configuration/hippo:domains/security-user-management:
      jcr:primaryType: hipposys:domain
      /users:
        jcr:primaryType: hipposys:domainrule
        /users-and-descendants:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:path
          hipposys:type: Reference
          hipposys:value: /hippo:configuration/hippo:users
      /groups:
        jcr:primaryType: hipposys:domainrule
        /groups-and-descendants:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:path
          hipposys:type: Reference
          hipposys:value: /hippo:configuration/hippo:groups
      /readonly:
        jcr:primaryType: hipposys:authrole
        hipposys:userrole: xm.security.viewer
        hipposys:role: readonly
      /readwrite:
        jcr:primaryType: hipposys:authrole
        hipposys:userrole: xm.security.user-admin
        hipposys:role: readwrite
