#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
#set($hyphen = '-')
#set($empty = '')
definitions:
  config:
    /hippo:configuration/hippo:modules/webfiles/hippo:moduleconfig:
      watchedModules: [repository-data/webfiles]
    /hippo:configuration/hippo:domains/hippofolders/readonly:
      hipposys:groups:
        operation: add
        type: string
        value: [sitewriters]
    /hippo:configuration/hippo:domains/preview-documents/readonly:
      hipposys:groups:
        operation: add
        type: string
        value: [previewusers]
    /hippo:configuration/hippo:domains/live-documents/readonly:
      hipposys:groups:
        operation: add
        type: string
        value: [liveusers]
# TODO SS: Remove this when hst refactoring (v13) will be over
    /hippo:configuration/hippo:frontend/cms/cms-services/hstRestProxyService:
      .meta:delete: true