#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
#set($hyphen = '-')
#set($empty = '')
definitions:
  config:
    /hippo:namespaces/${rootArtifactId.replace($hyphen,$empty)}/basedocument:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['mix:referenceable']
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['hipposysedit:remodel']
          hipposysedit:supertype: ['hippo:document', 'hippostdpubwf:document', 'hippostd:publishableSummary']
          hipposysedit:uri: http://www.onehippo.org/${rootArtifactId.replace($hyphen,$empty)}/nt/1.0
