definitions:
  config:
    /hippo:namespaces/hippoaddoncrispdemo/eventsdocument:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: 92a4c58a-b8dd-4974-b5e1-9947608745d5
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 9e2ed1a9-645d-4e48-93a6-d3c1a3ec8e0f
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['hipposysedit:remodel', 'mix:referenceable']
          jcr:uuid: ae79ee53-66c8-4047-9e7e-0779f765cb68
          hipposysedit:node: true
          hipposysedit:supertype: ['hippoaddoncrispdemo:basedocument', 'hippostd:relaxed',
            'hippotranslation:translated']
          hipposysedit:uri: http://www.onehippo.org/hippoaddoncrispdemo/nt/1.0
          /title:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hippoaddoncrispdemo:title
            hipposysedit:primary: false
            hipposysedit:type: String
          /introduction:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hippoaddoncrispdemo:introduction
            hipposysedit:primary: false
            hipposysedit:type: Text
          /content:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hippoaddoncrispdemo:content
            hipposysedit:primary: false
            hipposysedit:type: hippostd:html
          /date:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hippoaddoncrispdemo:date
            hipposysedit:primary: false
            hipposysedit:type: Date
          /enddate:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hippoaddoncrispdemo:enddate
            hipposysedit:primary: false
            hipposysedit:type: Date
          /image:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hippoaddoncrispdemo:image
            hipposysedit:primary: false
            hipposysedit:type: hippogallerypicker:imagelink
          /location:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: hippoaddoncrispdemo:location
            hipposysedit:primary: false
            hipposysedit:type: String
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: hippoaddoncrispdemo:eventsdocument
          jcr:mixinTypes: ['mix:referenceable']
          jcr:uuid: 7448ad8b-1546-43cc-95fa-e7a53d73b605
          hippo:related___pathreference: []
          hippoaddoncrispdemo:date: 0001-01-01T13:00:00+01:00
          hippoaddoncrispdemo:documenttype: event
          hippoaddoncrispdemo:enddate: 0001-01-01T13:00:00+01:00
          hippoaddoncrispdemo:introduction: ''
          hippoaddoncrispdemo:title: ''
          hippostd:holder: holder
          hippostd:state: draft
          hippostdpubwf:createdBy: ''
          hippostdpubwf:creationDate: 2013-09-16T18:03:51.692+02:00
          hippostdpubwf:lastModificationDate: 2013-09-16T18:03:51.691+02:00
          hippostdpubwf:lastModifiedBy: ''
          hippotranslation:id: document-type-locale-id
          hippotranslation:locale: document-type-locale
          /hippoaddoncrispdemo:content:
            jcr:primaryType: hippostd:html
            hippostd:content: <html><body></body></html>
          /hippoaddoncrispdemo:image:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          type: hippoaddoncrispdemo:eventsdocument
          /root:
            jcr:primaryType: frontend:plugin
            extension.left: ${cluster.id}.left
            extension.right: ${cluster.id}.right
            plugin.class: org.hippoecm.frontend.editor.layout.TwoColumn
            wicket.extensions: [extension.left, extension.right]
          /left:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.left.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.left
          /right:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.right.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.right
          /title:
            jcr:primaryType: frontend:plugin
            field: title
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /introduction:
            jcr:primaryType: frontend:plugin
            field: introduction
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /content:
            jcr:primaryType: frontend:plugin
            field: content
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /date:
            jcr:primaryType: frontend:plugin
            field: date
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /enddate:
            jcr:primaryType: frontend:plugin
            field: enddate
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /location:
            jcr:primaryType: frontend:plugin
            field: location
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /image:
            jcr:primaryType: frontend:plugin
            field: image
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
